# -*- coding: utf-8 -*-
"""land_crawler.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wdMZyNBIVO2khjG4JI5tV-aWggh0-t3k
"""

!pip install selenium
!apt-get update 
!apt install chromium-chromedriver

import requests
import json
from bs4 import BeautifulSoup
import bs4
import pandas as pd
import re
import numpy as np
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

chrome_options = Options()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
browser =webdriver.Chrome(options=chrome_options)

browser.get("https://plvr.land.moi.gov.tw/DownloadOpenData")
soup = BeautifulSoup(browser.page_source, "html.parser")
browser.find_element(By.XPATH, '//*[@id="ui-id-2"]').click() #選取非本期下載
nextPageElement = WebDriverWait(browser, 10).until(EC.presence_of_element_located((By.ID, "historySeason_id"))) #等待網頁加載完成，若未等待，無法搜尋到前季下載之選單
select = Select(browser.find_element(By.ID, 'historySeason_id')) #前季下載之下拉式選單
select.select_by_value('108S2') #選擇108年第2季
select2 = Select(browser.find_element(By.ID, 'fileFormatId')) 
select2.select_by_value('csv') #選擇下載格式csv
browser.find_element(By.XPATH,'//*[@id="downloadTypeId2"]').click() #選擇進階下載
#下載臺北市/新北市/桃園市/臺中市/高雄市之不動產買賣資料
browser.find_element(By.XPATH,'//*[@id="table5"]/tbody/tr[7]/td[2]/input').click()
browser.find_element(By.XPATH,'//*[@id="table5"]/tbody/tr[8]/td[2]/input').click()
browser.find_element(By.XPATH,'//*[@id="table5"]/tbody/tr[9]/td[2]/input').click()
browser.find_element(By.XPATH,'//*[@id="table5"]/tbody/tr[13]/td[2]/input').click()
browser.find_element(By.XPATH,'//*[@id="table5"]/tbody/tr[20]/td[2]/input').click()
#下載按鈕
download = browser.find_element(By.XPATH, '/html/body/div[1]/div[2]/div[1]/div[2]/table/tbody/tr[2]/td[2]/table/tbody/tr[2]/td/div/div/div[2]/div/table[3]/tbody/tr[1]/td[3]/input') 
browser.execute_script("arguments[0].click();", download)

!unzip /content/download.zip #colab上執行解壓縮